package com.tommyhasselman.termsconditions.model;

import java.util.List;
import java.util.ArrayList;
import java.util.Random;

/** Class Box that compares the contents of the box/parcel to what should be in the box/parcel */
public class Box extends GameObject {

    List<OrderItem> boxContains = new ArrayList<OrderItem>();

    List<OrderItem> boxShouldContain = new ArrayList<OrderItem>();

    /** Box constructor initialises both boxContains and boxShouldContain with items */
    public Box (int length) {
        int i = 0;

        /** Fills the box with random items generated by the BasicItem class */
        while (i < length){
            boxContains.add(new BasicItem());
            i++;
        }

        while (i < length){
            Random rand = new Random();
            int n = rand.nextInt(1);

            if n = 1



        }
    }

    public List<OrderItem> getBoxContains() {
        return boxContains;
    }

    public List<OrderItem> getBoxShouldContain() {
        return boxShouldContain;
    }
}
